ballerina-platform/module-ballerina-jsonutils

.github/workflows/build-master.yml, README.md
=> Update readme file

README.md, jsonutils-ballerina/build.gradle
=> Update minor change to readme

README.md, jsonutils-ballerina/src/jsonutils/jsonutils.bal, jsonutils-ballerina/src/jsonutils/tests/jsonutils_test.bal, jsonutils-native/src/main/java/org/ballerinalang/stdlib/jsonutils/XmlToJsonConverter.java
=> Add Ballerina class support

jsonutils-native/src/main/java/org/ballerinalang/stdlib/jsonutils/FromXML.java, jsonutils-native/src/main/java/org/ballerinalang/stdlib/jsonutils/XmlToJsonConverter.java, jsonutils-test-utils/src/main/java/org/ballerinalang/stdlib/jsonutils/testutils/JsonUtilsTestUtils.java
=> Migrate jBallerina Runtime APIs

.github/workflows/pull-request.yml, jsonutils-ballerina/src/jsonutils/jsonutils.bal
=> Update with isolated function changes

.github/workflows/publish-release.yml, .github/workflows/pull-request.yml, build.gradle, jsonutils-ballerina/build.gradle
=> Update the release workflow

.github/workflows/build-master.yml, .github/workflows/publish-release.yml, build.gradle
This will add separate triggers for the **Ballerina Standard Library Release Pipeline** and the **Build and Publish on Ballerina Lang change**
=> Add release and publish workflow triggers

jsonutils-native/src/main/java/module-info.java, jsonutils-native/src/main/java/org/ballerinalang/stdlib/jsonutils/FromTable.java, jsonutils-native/src/main/java/org/ballerinalang/stdlib/jsonutils/FromXML.java, jsonutils-native/src/main/java/org/ballerinalang/stdlib/jsonutils/XmlToJsonConverter.java, jsonutils-test-utils/src/main/java/module-info.java, jsonutils-test-utils/src/main/java/org/ballerinalang/stdlib/jsonutils/testutils/JsonUtilsTestUtils.java
Refactor ballerina runtime api usages
=> Migrate ballerina runtime apis

README.md
=> Update README.md issues and project section

gradle.properties
=> Upgrade ballerina version

jsonutils-ballerina/build.gradle
=> Fix cache packing

.github/workflows/publish-release.yml, jsonutils-ballerina/build.gradle
=> Fix ENV creation in the release workflow and enable docs

gradle.properties
=> Upgrade the Ballerina version

jsonutils-ballerina/build.gradle
> Update ballerina command to bal command
=> Update ballerina command to bal command

jsonutils-ballerina/jsonutils.bal, jsonutils-ballerina/tests/jsonutils_test.bal
Related Issue: ballerina-platform/ballerina-lang#28034
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
=> Change the name of the `java` langlib module to `jballerina.java`

jsonutils-ballerina/build.gradle
=> Avoid running tests twice when publishing

jsonutils-ballerina/build.gradle
> Renames the extension of the package distribution file from balo to bala 
> Fixes ballerina-platform/ballerina-lang#28476
=> Replace balo with bala

build.gradle, jsonutils-ballerina/build.gradle
Otherwise, it will publish without an updated Ballerina.toml file.
=> Re-order Build Tasks to Publish to the Ballerina Central

jsonutils-ballerina/build.gradle
=> Avoid publish SNAPSHOTs

.github/workflows/build-master.yml, .github/workflows/pull-request.yml, jsonutils-ballerina/build.gradle
=> Remove publishing code-coverage testable JAR and archive JSON

jsonutils-ballerina/build.gradle
> Add extracted bala in the zip artifact
> Fixes ballerina-platform/ballerina-lang#27763
=> Add extracted bala in the zip artifact

jsonutils-ballerina/build.gradle
> Add -c flag to build command
> Related to ballerina-platform/ballerina-lang#29032
=> Add -c flag to build command
